/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1bqn8gvaYM1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Login() {
  return (
    <div className="flex min-h-screen w-full">
      <div className="relative z-10 flex items-center justify-center h-full w-full">
        <div className="w-full max-w-md p-6 bg-background rounded-lg shadow-lg">
          <div className="space-y-6">
            <div className="space-y-2 text-center">
              <h1 className="text-3xl font-bold">Inicia sesion</h1>
              <p className="text-muted-foreground">Ingresa a tu centa para ver tus compras, pedidos y mas</p>
            </div>
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="email">Correo</Label>
                <Input id="email" type="email" placeholder="m@example.com" required />
              </div>
              <div className="space-y-2">
                <Label htmlFor="password">Contraseña</Label>
                <Input id="password" type="password" required />
              </div>
              <Button type="submit" className="w-full">
                ingresa
              </Button>
            </div>
            <div className="mt-4 text-center text-sm">
              ¿No tienes una cuenta?{" "}
              <Link href="/registro" className="underline" prefetch={false}>
                Crea una
              </Link>
            </div>
          </div>
        </div>
      </div>
      <div className="relative w-full md:w-1/2 lg:w-2/3 h-96">
  <img src="/inicio.webp" alt="Background image" className="object-contain h-full w-full" />
  <div className="absolute inset-0 bg-black/50 z-0" />
</div>




    </div>
  )
}
