/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/eIuL2f9DmGT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Cormorant_Garamond } from 'next/font/google'
import { Judson } from 'next/font/google'

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { SVGProps } from "react"

export function Pedidos() {
  return (
    <div className="flex flex-col w-full min-h-screen bg-[#f5f5f5]">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6 bg-[#0077b6] text-white">
        <Link href="#" className="flex items-center gap-2 text-lg font-semibold" prefetch={false}>
          <Package2Icon className="w-6 h-6" />
          <span>Papelería Acme</span>
        </Link>
        <nav className="ml-auto flex items-center gap-6 text-sm font-medium">
          <Link href="#" className="hover:underline" prefetch={false}>
            Inicio
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Pedidos
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Productos
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Clientes
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Reportes
          </Link>
        </nav>
        <div className="ml-auto flex items-center gap-4">
          <Button variant="outline" size="icon" className="rounded-full bg-[#0077b6] text-white hover:bg-[#005a8f]">
            <BellIcon className="w-5 h-5" />
            <span className="sr-only">Notificaciones</span>
          </Button>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Avatar className="h-9 w-9 bg-[#0077b6] text-white">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>JP</AvatarFallback>
                <span className="sr-only">Toggle user menu</span>
              </Avatar>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>Mi Cuenta</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Configuración</DropdownMenuItem>
              <DropdownMenuItem>Cerrar Sesión</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <main className="flex-1 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 p-4 md:p-6">
        <div className="col-span-1 md:col-span-2 lg:col-span-2">
          <Card className="bg-white shadow-md">
            <CardHeader>
              <CardTitle className="text-[#0077b6]">Pedidos Pendientes</CardTitle>
              <CardDescription className="text-[#666666]">
                Estos son los pedidos que aún no han sido entregados.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="text-[#0077b6]">Pedido</TableHead>
                    <TableHead className="text-[#0077b6]">Cliente</TableHead>
                    <TableHead className="text-[#0077b6]">Dirección</TableHead>
                    <TableHead className="text-[#0077b6]">Fecha</TableHead>
                    <TableHead className="text-[#0077b6]">Acción</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>
                      <div className="font-medium text-[#0077b6]">OD-12346</div>
                    </TableCell>
                    <TableCell>
                      <div className="font-medium text-[#0077b6]">María Gómez</div>
                      <div className="text-[#666666]">maria@example.com</div>
                    </TableCell>
                    <TableCell>
                      <div className="text-[#666666]">Avenida Central 456</div>
                      <div className="text-[#666666]">Medellín, Colombia</div>
                    </TableCell>
                    <TableCell className="text-[#666666]">2023-05-16</TableCell>
                    <TableCell>
                      <Button size="sm" className="mr-2 bg-[#0077b6] text-white hover:bg-[#005a8f]">
                        Marcar como Entregado
                      </Button>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <div className="font-medium text-[#0077b6]">OD-12347</div>
                    </TableCell>
                    <TableCell>
                      <div className="font-medium text-[#0077b6]">Juan Pérez</div>
                      <div className="text-[#666666]">juan@example.com</div>
                    </TableCell>
                    <TableCell>
                      <div className="text-[#666666]">Calle Principal 123</div>
                      <div className="text-[#666666]">Bogotá, Colombia</div>
                    </TableCell>
                    <TableCell className="text-[#666666]">2023-05-17</TableCell>
                    <TableCell>
                      <Button size="sm" className="mr-2 bg-[#0077b6] text-white hover:bg-[#005a8f]">
                        Marcar como Entregado
                      </Button>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <div className="font-medium text-[#0077b6]">OD-12348</div>
                    </TableCell>
                    <TableCell>
                      <div className="font-medium text-[#0077b6]">Ana Rodríguez</div>
                      <div className="text-[#666666]">ana@example.com</div>
                    </TableCell>
                    <TableCell>
                      <div className="text-[#666666]">Carrera 45 #67-89</div>
                      <div className="text-[#666666]">Cali, Colombia</div>
                    </TableCell>
                    <TableCell className="text-[#666666]">2023-05-18</TableCell>
                    <TableCell>
                      <Button size="sm" className="mr-2 bg-[#0077b6] text-white hover:bg-[#005a8f]">
                        Marcar como Entregado
                      </Button>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <div className="font-medium text-[#0077b6]">OD-12349</div>
                    </TableCell>
                    <TableCell>
                      <div className="font-medium text-[#0077b6]">Carlos Sánchez</div>
                      <div className="text-[#666666]">carlos@example.com</div>
                    </TableCell>
                    <TableCell>
                      <div className="text-[#666666]">Avenida 10 #23-45</div>
                      <div className="text-[#666666]">Barranquilla, Colombia</div>
                    </TableCell>
                    <TableCell className="text-[#666666]">2023-05-19</TableCell>
                    <TableCell>
                      <Button size="sm" className="mr-2 bg-[#0077b6] text-white hover:bg-[#005a8f]">
                        Marcar como Entregado
                      </Button>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <div className="font-medium text-[#0077b6]">OD-12352</div>
                    </TableCell>
                    <TableCell>
                      <div className="font-medium text-[#0077b6]">Luisa Fernández</div>
                      <div className="text-[#666666]">luisa@example.com</div>
                    </TableCell>
                    <TableCell>
                      <div className="text-[#666666]">Calle 67 #89-12</div>
                      <div className="text-[#666666]">Medellín, Colombia</div>
                    </TableCell>
                    <TableCell className="text-[#666666]">2023-05-20</TableCell>
                    <TableCell>
                      <Button size="sm" className="mr-2 bg-[#0077b6] text-white hover:bg-[#005a8f]">
                        Marcar como Entregado
                      </Button>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>
        <div className="col-span-1 md:col-span-2 lg:col-span-1">
          <Card className="bg-white shadow-md">
            <CardHeader>
              <CardTitle className="text-[#0077b6]">Pedidos Entregados</CardTitle>
              <CardDescription className="text-[#666666]">
                Estos son los pedidos que ya han sido entregados.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="text-[#0077b6]">Pedido</TableHead>
                    <TableHead className="text-[#0077b6]">Cliente</TableHead>
                    <TableHead className="text-[#0077b6]">Dirección</TableHead>
                    <TableHead className="text-[#0077b6]">Fecha</TableHead>
                    <TableHead className="text-[#0077b6]">Acción</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>
                      <div className="font-medium text-[#0077b6]">OD-12345</div>
                    </TableCell>
                    <TableCell>
                      <div className="font-medium text-[#0077b6]">Juan Pérez</div>
                      <div className="text-[#666666]">juan@example.com</div>
                    </TableCell>
                    <TableCell>
                      <div className="text-[#666666]">Calle Principal 123</div>
                      <div className="text-[#666666]">Bogotá, Colombia</div>
                    </TableCell>
                    <TableCell className="text-[#666666]">2023-05-15</TableCell>
                    <TableCell>
                      <Button size="sm" className="mr-2 bg-[#0077b6] text-white hover:bg-[#005a8f]">
                        Marcar como Pendiente
                      </Button>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <div className="font-medium text-[#0077b6]">OD-12350</div>
                    </TableCell>
                    <TableCell>
                      <div className="font-medium text-[#0077b6]">Sofía Gómez</div>
                      <div className="text-[#666666]">sofia@example.com</div>
                    </TableCell>
                    <TableCell>
                      <div className="text-[#666666]">Carrera 78 #12-34</div>
                      <div className="text-[#666666]">Medellín, Colombia</div>
                    </TableCell>
                    <TableCell className="text-[#666666]">2023-05-20</TableCell>
                    <TableCell>
                      <Button size="sm" className="mr-2 bg-[#0077b6] text-white hover:bg-[#005a8f]">
                        Marcar como Pendiente
                      </Button>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <div className="font-medium text-[#0077b6]">OD-12351</div>
                    </TableCell>
                    <TableCell>
                      <div className="font-medium text-[#0077b6]">Andrés Ramírez</div>
                      <div className="text-[#666666]">andres@example.com</div>
                    </TableCell>
                    <TableCell>
                      <div className="text-[#666666]">Calle 45 #67-89</div>
                      <div className="text-[#666666]">Cali, Colombia</div>
                    </TableCell>
                    <TableCell className="text-[#666666]">2023-05-21</TableCell>
                    <TableCell>
                      <Button size="sm" className="mr-2 bg-[#0077b6] text-white hover:bg-[#005a8f]">
                        Marcar como Pendiente
                      </Button>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>
        <div className="col-span-1 md:col-span-2 lg:col-span-3 mt-4">
          <Card className="bg-white shadow-md">
            <CardHeader>
              <CardTitle className="text-[#0077b6]">Estadísticas de Ventas</CardTitle>
              <CardDescription className="text-[#666666]">
                Analiza el rendimiento de tus ventas a lo largo del tiempo.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 gap-4">
                <div className="bg-[#f5f5f5] rounded-lg p-4">
                  <h3 className="text-lg font-medium mb-2 text-[#0077b6]">Ventas Mensuales</h3>
                  <div className="flex items-center justify-between">
                    <div className="text-4xl font-bold text-[#0077b6]">$45,231.89</div>
                    <div className="text-sm text-[#666666]">+20.1% desde el mes pasado</div>
                  </div>
                </div>
                <div className="bg-[#f5f5f5] rounded-lg p-4">
                  <h3 className="text-lg font-medium mb-2 text-[#0077b6]">Suscripciones</h3>
                  <div className="flex items-center justify-between">
                    <div className="text-4xl font-bold text-[#0077b6]">+2,350</div>
                    <div className="text-sm text-[#666666]">+180.1% desde el mes pasado</div>
                  </div>
                </div>
                <div className="bg-[#f5f5f5] rounded-lg p-4 col-span-2">
                  <h3 className="text-lg font-medium mb-2 text-[#0077" />
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}

function BellIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  )
}


function Package2Icon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}
