/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/IucIangNjYU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Registro() {
  return (
    <div className="flex min-h-screen w-full">
      <div className="relative z-10 flex items-center justify-center h-full w-full">
        <div className="w-full max-w-md p-6 bg-background rounded-lg shadow-lg">
          <div className="space-y-6">
            <div className="space-y-2 text-center">
              <h1 className="text-3xl font-bold">Registrate</h1>
              <p className="text-muted-foreground">Crea tu cuenta</p>
            </div>
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="name">Nombre</Label>
                <Input id="name" type="text" placeholder="Nombre" required />
              </div>
              <div className="space-y-2">
                <Label htmlFor="lastName">Apellido</Label>
                <Input id="lastName" type="text" placeholder="Apellido" required />
              </div>
              <div className="space-y-2">
                <Label htmlFor="phone">Numero de celular</Label>
                <Input id="phone" type="tel" placeholder="+57 (333) 000-5555" required />
              </div>
              <div className="space-y-2">
                <Label htmlFor="email">Correo electronico</Label>
                <Input id="email" type="email" placeholder="m@gmail.com" required />
              </div>
              <div className="space-y-2">
                <Label htmlFor="address">Direccion</Label>
                <Input id="address" type="text" placeholder="Carrera 100" required />
              </div>
              <Button type="submit" className="w-full">
                Crear cuenta
              </Button>
            </div>
            <div className="mt-4 text-center text-sm">
              ¿Ya tienes cuenta?{" "}
              <Link href="/login" className="underline" prefetch={false}>
                Inicia sesión.
              </Link>
            </div>
          </div>
        </div>
      </div>
      <div className="relative w-full md:w-1/2 lg:w-2/3 h-80">
        <img src="/imagenes.jpg" alt="Background image" className="object-cover object-center h-full w-full" />
        <div className="absolute inset-0 bg-black/50 z-0" />
      </div>



    </div>
  )
}
